Update CI-CD.yml

diff --git a/.github/workflows/CI-CD.yml b/.github/workflows/CI-CD.yml
--- a/.github/workflows/CI-CD.yml
+++ b/.github/workflows/CI-CD.yml
@@ -70,11 +70,11 @@ jobs:
         id: plan
 #         if: github.event_name == 'pull_request'
         run: terraform plan -var="tag_version=${{ github.sha }}" -var="db_uri=${{ secrets.PROD_MONGODB_URI }}"
-        continue-on-error: true
+#        continue-on-error: true
             
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+#       - name: Terraform Plan Status
+#         if: steps.plan.outcome == 'failure'
+#         run: exit 1
         
       - name: Terraform Apply
 #         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
